[PCFG-98] Added oauth2_authorization field
pagopa/azurerm pull request #136
Opened 2021-12-14 11:29 UTC by aomegax

### List of changes

### Motivation and context

### Type of changes

- [ ] Add new module
- [X] Update existing module
- [ ] Remove existing module

### Does this introduce a breaking change?

- [ ] Yes
- [X] No

### Other information

2021-12-15 17:36 UTC, uolter requested changes

2021-12-15 17:36 UTC, uolter commented on api_management_api/main.tf
> +    authorization_server_name   = var.oauth2_authorization.authorization_server_name != null ? var.oauth2_authorization.authorization_server_name : null
I have the fear this not working since the authorization_server_name is required. Provided that it can't be null.
This change is not backward compatible though.

2021-12-16 08:18 UTC, pasqualespica commented on api_management_api/main.tf
> +    authorization_server_name   = var.oauth2_authorization.authorization_server_name != null ? var.oauth2_authorization.authorization_server_name : null
right, refacts oauth2 authorization using `dynamic`

2021-12-16 08:45 UTC, uolter approved these changes

2021-12-16 10:07 UTC, pasqualespica approved these changes

2021-12-16 10:12 UTC, merged