Cen 1293 data factory module
pagopa/azurerm pull request #171
Opened 2022-01-19 15:04 UTC by GiovanniMancini

This PR proposes to create a new `data_factory` module to create data factories. 

### List of changes

- Data factory module supporting private endpoint connections, managed vnet and managed private endpoints to connect to data sources and sinks 

### Motivation and context

This PR is motivated by the fact that `cstar` supports a _data ingestion_ use case, which is best resolved by ETL/ELT pipelines, thus avoiding an overuse of queue and event-hubs. 

### Type of changes

- [x] Add new module
- [ ] Update existing module
- [ ] Remove existing module

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

### Other information

2022-01-19 15:20 UTC, uolter requested changes

2022-01-19 15:20 UTC, uolter commented on data_factory/main.tf
> +resource "azurerm_data_factory" "df" {
```suggestion
resource "azurerm_data_factory" "this" {
```

2022-01-19 15:20 UTC, uolter commented on data_factory/main.tf
> +resource "azurerm_private_endpoint" "pe" {
```suggestion
resource "azurerm_private_endpoint" "this" {
```

2022-01-19 15:20 UTC, uolter commented on data_factory/main.tf
> +resource "azurerm_private_dns_a_record" "record" {
```suggestion
resource "azurerm_private_dns_a_record" "this" {
```

2022-01-19 15:20 UTC, uolter commented on data_factory/main.tf
> +  name                   = format("%s-%s-data-factory", var.name_prefix, var.name)
```suggestion
  name                   = format("%s-data-factory",  var.name)
```

2022-01-19 15:20 UTC, uolter commented on data_factory/main.tf
> +  name                = format("%s-%s-private-endpoint", var.name_prefix, var.name)
```suggestion
  name                = format("%s-%s-private-endpoint", var.name)
```

2022-01-19 15:20 UTC, uolter commented on data_factory/main.tf
> +    name = format("%s-%s-private-dns-zone-group", var.name_prefix, var.name)
```suggestion
    name = format("%s-private-dns-zone-group", var.name)
```

2022-01-19 15:20 UTC, uolter commented on data_factory/variables.tf
> +variable "name_prefix" {
We do not need a prefix

2022-01-19 15:20 UTC, uolter commented on data_factory/main.tf
> +  managed_virtual_network_enabled = true
```suggestion
  managed_virtual_network_enabled = true 
  
   tags = var.tags 
 
```

2022-01-19 15:20 UTC, uolter commented on data_factory/main.tf
> +  managed_virtual_network_enabled = true
Tags are missed https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory#argument-reference

2022-01-19 15:44 UTC, GiovanniMancini commented on data_factory/main.tf
> +  name                   = format("%s-%s-data-factory", var.name_prefix, var.name)
@uolter thank you for your review and suggestions. I'll expand a bit on the rationale of using different variables for prefix and name. The `name_prefix` usually contains the string `project-d`, `project-u` or `project-p` depending on the environment. Since the `name` variable, in this case, is also used to create the `A` record in the private dns zone, I thought it was better to have separate variables. Maybe I could rename the `name` as `dns_record_name` and format the other names using only `name_prefix` . Could it be a nice solution for you?

2022-01-19 15:47 UTC, uolter commented on data_factory/main.tf
> +  name                   = format("%s-%s-data-factory", var.name_prefix, var.name)
It looks great to me

2022-01-19 17:10 UTC, pasqualedevita requested changes

2022-01-19 17:10 UTC, pasqualedevita commented on data_factory/main.tf
> +resource "azurerm_private_dns_a_record" "record" {
azurerm_private_dns_a_record is added by azure when u set private_dns_zone_group, so we can remove this record

2022-01-19 17:10 UTC, pasqualedevita commented on data_factory/main.tf
> +resource "azurerm_private_endpoint" "pe" {
maybe not all data factory will be private, better to add a variable like here to manage private/public resources

https://github.com/pagopa/azurerm/blob/main/redis_cache/main.tf#L42
https://github.com/pagopa/azurerm/blob/main/redis_cache/variables.tf#L39

2022-01-19 17:13 UTC, pasqualedevita commented
also run a `terraform fmt`

2022-01-19 17:17 UTC, GiovanniMancini commented on data_factory/main.tf
> +resource "azurerm_private_dns_a_record" "record" {
@pasqualedevita Thank you for your suggestion. I added another A record to allow module users to fully customize the name, as the default one has a not so intuitive naming scheme

2022-01-19 19:59 UTC, uolter approved these changes

2022-01-19 19:59 UTC, uolter commented on data_factory/main.tf
> +  public_network_enabled = !(var.private_endpoint.enabled)
```suggestion
  public_network_enabled = !var.private_endpoint.enabled
```

2022-01-20 08:46 UTC, pasqualedevita requested changes

2022-01-20 08:46 UTC, pasqualedevita commented on data_factory/main.tf
> +resource "azurerm_private_dns_a_record" "record" {
using a custom name probably u need also a custom SSL certificate.
Anyway I suggest 2 ways:
1. remove `dns_a_record_name` and create custom name for all 
2. rename `dns_a_record_name` in `custom_domain_enabled` for more explicit variable

2022-01-20 13:23 UTC, GiovanniMancini commented on data_factory/main.tf
> +resource "azurerm_private_dns_a_record" "record" {
> using a custom name probably u need also a custom SSL certificate. Anyway I suggest 2 ways:
> 
> 1. remove `dns_a_record_name` and create custom name for all
> 2. rename `dns_a_record_name` in `custom_domain_enabled` for more explicit variable (I see `name = var.name` and not `var.dns_a_record_name`)

@pasqualedevita I renamed the variable. Maybe now the semantic is more explicit

2022-01-21 13:09 UTC, pasqualedevita requested changes

2022-01-21 13:09 UTC, pasqualedevita commented on data_factory/main.tf
> +  name                   = format("%s-data-factory", var.name)
Set only to name=var.name in this way module is more general and flexible

2022-01-21 14:55 UTC, GiovanniMancini commented on data_factory/main.tf
> +  name                   = format("%s-data-factory", var.name)
OK, thank you for pointing out

2022-01-21 17:37 UTC, pasqualedevita reviewed
add tags

2022-01-21 17:37 UTC, pasqualedevita commented on data_factory/main.tf
> +  }
```suggestion
  }

  tags = var.tags
```

2022-01-21 17:37 UTC, pasqualedevita commented on data_factory/main.tf
> +}
```suggestion

  tags = var.tags
}
```

2022-01-21 17:41 UTC, pasqualedevita approved these changes

2022-01-24 14:45 UTC, merged