Function app can have system identity
pagopa/azurerm pull request #267
Opened 2022-11-11 14:44 UTC by manuelcoppotelli

### List of changes

Added a variable which enable the generation of a system identity for the function app

### Motivation and context

So that functionsapp can interact with other resources without many connection strings.

### Type of changes

- [ ] Add new module
- [x] Update existing module
- [ ] Remove existing module

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

### Run checks

Useful commands to run checks on local machine

```sh
bash .utils/terraform_run_all.sh init local
pre-commit run -a
```

2022-11-11 15:23 UTC, diegolagospagopa requested changes
Please can you add an example in the README so is possible to understand better how to use the module

2022-11-11 15:23 UTC, diegolagospagopa commented on function_app/variables.tf
> +}
Please can you add
1. a description
2. change the name is something like `system_identity_enabled` o something like this, to understand that is a boolean

2022-11-11 16:03 UTC, manuelcoppotelli commented on function_app/variables.tf
> +}
fixed

2022-11-13 12:23 UTC, diegolagospagopa approved these changes

2022-11-14 07:53 UTC, merged