[#IP-431] add function_app module
pagopa/azurerm pull request #87
Opened 2021-10-05 16:47 UTC by fabriziopapi

Add function_app module configuration

2021-10-05 17:55 UTC, uolter reviewed
Not blocking 
https://www.terraform-best-practices.com/naming
> Do not repeat resource type in resource name (not partially, nor completely):
Good: resource "aws_route_table" "public" {}
Bad: resource "aws_route_table" "public_route_table" {}
Bad: resource "aws_route_table" "public_aws_route_table" {}

> **Resource name should be named this if there is no more descriptive and general name** available, or if resource module creates single resource of this type (eg, there is single resource of type aws_nat_gateway and multiple resources of typeaws_route_table, so aws_nat_gateway should be named this and aws_route_table should have more descriptive names - like private, public, database).

2021-10-06 06:31 UTC, pasqualedevita requested changes
u can try a plan creating a new branch on `io-infra` and pointing ref to this branch

2021-10-06 06:31 UTC, pasqualedevita commented on function_app/main.tf
> +}
```suggestion
```
u can delete this, now we can pass these values in safe mode without this

2021-10-06 06:31 UTC, pasqualedevita commented on function_app/main.tf
> +}
```suggestion
```
u can delete this, now we can pass these values in safe mode without this

2021-10-06 06:31 UTC, pasqualedevita commented on function_app/main.tf
> +    module.secrets_from_keyvault.secrets_with_value,
```suggestion
```
same

2021-10-06 06:31 UTC, pasqualedevita commented on function_app/main.tf
> +}
```suggestion
```
u can delete this, we create subnet outside fnapp

2021-10-06 06:31 UTC, pasqualedevita commented on function_app/main.tf
> +}
this is important do not delete it :)

2021-10-06 09:29 UTC, fabriziopapi commented on function_app/main.tf
> +}
I will keep it safe and sound!

2021-10-06 10:16 UTC, fabriziopapi commented
> Not blocking https://www.terraform-best-practices.com/naming
> 
> > Do not repeat resource type in resource name (not partially, nor completely):
> > Good: resource "aws_route_table" "public" {}
> > Bad: resource "aws_route_table" "public_route_table" {}
> > Bad: resource "aws_route_table" "public_aws_route_table" {}
> 
> > **Resource name should be named this if there is no more descriptive and general name** available, or if resource module creates single resource of this type (eg, there is single resource of type aws_nat_gateway and multiple resources of typeaws_route_table, so aws_nat_gateway should be named this and aws_route_table should have more descriptive names - like private, public, database).

Fixed!

2021-10-06 10:26 UTC, uolter approved these changes

2021-10-06 10:27 UTC, merged

2021-10-06 10:27 UTC, pasqualedevita commented on function_app/variables.tf
> +  })
```suggestion
```

2021-10-06 10:28 UTC, pasqualedevita commented on function_app/main.tf
> +  count = var.virtual_network_info == null ? 0 : 1
```suggestion
  count = var. subnet_id == null ? 0 : 1
```

2021-10-06 10:28 UTC, pasqualedevita commented on function_app/variables.tf
> +  })
remove `virtual_network_info`

2021-10-06 10:29 UTC, pasqualedevita commented on function_app/variables.tf
> +# }
```suggestion
```
not used

2021-10-06 10:29 UTC, pasqualedevita commented on function_app/variables.tf
> +# }
```suggestion
```
not used

2021-10-06 10:30 UTC, pasqualedevita commented on function_app/variables.tf
> +}
```suggestion
```
not used